function listvolumes(obj)

for i = 1:numel(obj.volumeStorage.names)
    fprintf(' %s) %s\n\tSize: %s\n\t%s\n\t%s\n',num2str(i),...
        obj.volumeStorage.names{i},...
        mat2str(obj.volumeStorage.list{i}.volumeInfo.dimensions),...
        obj.volumeStorage.list{i}.volumeInfo.modality,...
        obj.volumeStorage.list{i}.volumeInfo.scanDirection)
end
end